Bluetooth: virtio_bt: Use virtio_cread16 instead of virtio_cread
Using virtio_cread leads to a warning on PowerPC architecture:

drivers/bluetooth/virtio_bt.c:303:17: sparse:    bad type *
drivers/bluetooth/virtio_bt.c:303:17: sparse:    unsigned short *
drivers/bluetooth/virtio_bt.c:303:17: sparse: sparse: incompatible types in comparison expression (different base types):
drivers/bluetooth/virtio_bt.c:303:17: sparse: sparse: no generic selection for 'unsigned short [addressable] virtio_cread_v'
drivers/bluetooth/virtio_bt.c:303:17: sparse: sparse: no generic selection for 'unsigned short virtio_cread_v'

Since the values are defined as 16-bit, just use virtio_cread16 instead.

Fixes: 148a48f61393 ("Bluetooth: Add support for virtio transport driver")
Signed-off-by: Marcel Holtmann <marcel@holtmann.org>