Bluetooth: hci_ll: Fix compilation issue
hci_ll.c: In function ‘ll_setup’:
hci_ll.c:656:68: error: ‘struct hci_dev’ has no member
                 named ‘quirks’
	set_bit(HCI_QUIRK_INVALID_BDADDR, &hu->hdev->quirks);

Fixes: be736f5f89d5 ("Bluetooth: hci_dev: replace 'quirks' integer by 'quirk_flags' bitmap")
Signed-off-by: Kiran K <kiran.k@intel.com>